spring.application.name=scanner
spring.data.mongodb.uri=mongodb+srv://reddirani8919:odtJ8MqMWJ74e9zB@cluster0.p1qf2ei.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=scann